In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataLink = "https://data.cityofchicago.org/resource/t7ek-mgzi.json?$order=id&$limit=100000&$offset=0"
data = pd.read_json(dataLink)

data

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,28545,JJ100205,2025-01-01 03:57:00,094XX S HARVARD AVE,0110,HOMICIDE,FIRST DEGREE MURDER,YARD,False,False,...,9,49,01A,1175662.0,1842226.0,2025,2025-01-09T15:41:07.000,41.722435,-87.632169,"{'type': 'Point', 'coordinates': [-87.63216880..."
1,28546,JJ100293,2025-01-01 06:10:00,022XX S CENTRAL PARK AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,True,...,22,30,01A,1152723.0,1888730.0,2025,2025-02-15T15:41:00.000,41.850530,-87.714967,"{'type': 'Point', 'coordinates': [-87.71496693..."
2,28547,JJ100596,2025-01-01 14:06:00,075XX S RACINE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,TAVERN,False,False,...,17,71,01A,1169629.0,1854690.0,2025,2025-01-09T15:41:07.000,41.756770,-87.653906,"{'type': 'Point', 'coordinates': [-87.65390643..."
3,28548,JJ100160,2025-01-02 01:18:00,012XX S SAWYER AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,...,24,29,01A,1154891.0,1894243.0,2025,2025-01-10T15:41:24.000,41.865616,-87.706862,"{'type': 'Point', 'coordinates': [-87.70686228..."
4,28549,JJ100988,2025-01-01 20:15:00,015XX W WARREN BLVD,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,False,...,27,28,01A,1166006.0,1900436.0,2025,2025-01-09T15:41:07.000,41.882380,-87.665882,"{'type': 'Point', 'coordinates': [-87.66588180..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28263,13760161,JJ163061,2025-01-29 12:00:00,078XX S EXCHANGE AVE,0915,MOTOR VEHICLE THEFT,"TRUCK, BUS, MOTOR HOME",OTHER COMMERCIAL TRANSPORTATION,False,False,...,7,43,07,NaN,NaN,2025,2025-02-27T15:41:01.000,NaN,NaN,NaN
28264,13760168,JJ162055,2025-01-15 00:00:00,073XX S RACINE AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,ALLEY,False,True,...,17,67,17,NaN,NaN,2025,2025-02-27T15:41:01.000,NaN,NaN,NaN
28265,13760202,JJ163210,2025-02-18 00:01:00,049XX S MICHIGAN AVE,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,3,38,05,NaN,NaN,2025,2025-02-27T15:41:01.000,NaN,NaN,NaN
28266,13760249,JJ163218,2025-01-05 02:00:00,035XX N CLARK ST,0810,THEFT,OVER $500,BAR OR TAVERN,False,False,...,44,6,06,NaN,NaN,2025,2025-02-27T15:41:01.000,NaN,NaN,NaN
28267,13760376,JJ161260,2025-02-15 18:00:00,079XX S NORMAL AVE,0820,THEFT,$500 AND UNDER,APARTMENT,False,False,...,6,44,06,NaN,NaN,2025,2025-02-27T15:41:01.000,NaN,NaN,NaN

In [47]:
data.shape

(10000, 22)